#version 450

// #extension GL_EXT_debug_printf : enable

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (set = 0, binding = 0) buffer BatchIndex {
    uint currBatchIndex[]; // 0 - atomic counter, 1 - current index
};

layout(set = 0, binding = 1) readonly buffer BatchIndices
{
    uint batchIndices[];
};

void main() {
    uint idx = currBatchIndex[0];
    currBatchIndex[1] = batchIndices[idx];

    currBatchIndex[0] += 1;
    // atomicAdd(currBatchIndex[0], 1);

    // debugPrintfEXT("aaa %d %d %d\n", idx, currBatchIndex[0], currBatchIndex[1]);
}